servers:
  - serverId: 0
    host: "localhost"
    port: "8080"
  - serverId: 1
    host: "localhost"
    port: "8081"
  - serverId: 2
    host: "localhost"
    port: "8082"
  - serverId: 3
    host: "localhost"
    port: "8083"
